"""create fruits table

Revision ID: 292e3557975e
Revises: 
Create Date: 2026-01-07 18:04:48.725595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '292e3557975e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fruits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sa.Enum('CITRUS', 'TROPICAL', 'BERRY', 'STONE', 'OTHER', name='fruitcategory'), nullable=False),
    sa.Column('season', sa.Enum('SUMMER', 'WINTER', 'AUTUMN', 'SPRING', 'ALL_YEAR', name='season'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit', sa.Enum('KG', 'UNIT', 'BOX', name='unit'), nullable=False),
    sa.Column('min_stock', sa.Integer(), nullable=False),
    sa.Column('origin_type', sa.Enum('NATIONAL', 'IMPORTED', name='origintype'), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fruits')
    # ### end Alembic commands ###
